(() => {
    'use strict';
    EAS.Modules ||= {};
    const troopReadiness = (villageId) => { const metadata=EAS.Data.Troops.getMetadata();if(metadata.stale)return{label:'Dados stale',tone:'warning'};const village=EAS.Data.Troops.getById(villageId);if(!village)return{label:'Indeterminado',tone:'muted'};const troops=village.available||village.ownHome||village.troops||{};return Object.values(troops).some((value)=>Number(value)>0)?{label:'Pronta',tone:'success'}:{label:'Sem tropas suficientes',tone:'warning'}; };
    const showSummary = (summary = {}) => { const win=EAS.UI.createWindow({id:'eas-mass-farm-summary',title:'🌾 Farm em Massa concluído',width:520});win.body.innerHTML=`<div class="eas-status eas-status--success">Execução finalizada.</div><div class="fake-execution-summary"><div><strong>Aldeias selecionadas</strong><span>${summary.selected||0}</span></div><div><strong>Concluídas</strong><span>${summary.completed||0}</span></div><div><strong>Puladas</strong><span>${summary.skipped||0}</span></div><div><strong>Erros</strong><span>${summary.errors||0}</span></div><div><strong>Ataques enviados</strong><span>${summary.attacksSent||0}</span></div><div><strong>Tempo total</strong><span>${Math.round(Number(summary.durationMs||0)/1000)}s</span></div></div>`;win.body.appendChild(EAS.UI.createButton({text:'Voltar ao menu',onClick:()=>{win.close();EAS.UI.openMainWindow();}}));return win; };
    if (!window.__easMassFarmSummaryListener) { window.__easMassFarmSummaryListener=true;window.addEventListener('message',(event)=>{if(event.origin!==location.origin||event.data?.source!=='eas-tw-hub'||event.data?.executionType!=='mass-farm')return;showSummary(event.data.summary);}); }
    EAS.Modules.MassFarm = { troopReadiness,showSummary,open:async()=>{
        EAS.Usage?.track?.('farm.mass.open');await EAS.Data.Villages.ensureFresh();await EAS.Data.Groups.ensureFresh();
        const win=EAS.UI.createWindow({id:'eas-mass-farm',title:'🌾 Farm em Massa',width:760,className:'mass-farm-window'});const root=document.createElement('div');root.className='eas-form mass-farm';
        const groupSelect=document.createElement('select');groupSelect.className='eas-input';[{id:'all',name:'Todos'},...EAS.Data.Groups.getAll()].forEach((group)=>groupSelect.add(new Option(group.name,group.id)));
        const templateSelect=document.createElement('select');templateSelect.className='eas-input';templateSelect.add(new Option('A','A'));
        const intervalInput=EAS.UI.createInput({type:'number',value:'1',min:'1'});intervalInput.step='0.1';
        const list=document.createElement('div');list.className='mass-farm-villages eas-table-wrapper';const count=document.createElement('strong');const status=document.createElement('div');
        const selectionActions=document.createElement('div');selectionActions.className='eas-actions';const selectAll=EAS.UI.createButton({text:'Selecionar todas'}),clearAll=EAS.UI.createButton({text:'Desmarcar todas',className:'eas-button--secondary'});selectionActions.append(selectAll,clearAll);
        const actions=document.createElement('div');actions.className='eas-actions';const start=EAS.UI.createButton({text:'Iniciar Farm em Massa'});const back=EAS.UI.createButton({text:'Voltar ao menu',className:'eas-button--secondary',onClick:()=>{win.close();EAS.UI.openMainWindow();}});actions.append(start,back);
        root.append(EAS.UI.createField({label:'Grupo de origem',input:groupSelect}),EAS.UI.createField({label:'Modelo',input:templateSelect,helpText:'O Modelo A é configurado no próprio Tribal Wars.'}),EAS.UI.createField({label:'Intervalo entre envios (segundos)',input:intervalInput,helpText:'Mínimo seguro: 1 segundo.'}),selectionActions,list,count,status,actions);win.body.appendChild(root);
        const selectedIds=()=>[...list.querySelectorAll('input[type="checkbox"]:checked')].map((input)=>input.value);const updateCount=()=>{const selected=selectedIds().length;count.textContent=`Selecionadas: ${selected}`;start.disabled=selected===0;};
        const renderVillages=()=>{const ids=new Set(EAS.Data.Groups.getVillageIds(groupSelect.value).map(String));const villages=EAS.Data.Villages.getAll().filter((village)=>ids.has(String(village.id)));list.innerHTML='';if(!villages.length){list.innerHTML='<div class="eas-status eas-status--info">Este grupo não possui aldeias.</div>';updateCount();return;}const table=document.createElement('table');table.className='eas-table';table.innerHTML='<thead><tr><th></th><th>Aldeia</th><th>Pré-checagem</th></tr></thead><tbody></tbody>';villages.forEach((village)=>{const readiness=troopReadiness(village.id),row=document.createElement('tr');row.innerHTML=`<td><input type="checkbox" value="${village.id}" checked></td><td>${EAS.Utils.escapeHtml(village.name)}${village.coordinate?` · ${village.coordinate}`:''}</td><td><span class="eas-status--${readiness.tone}">${readiness.label}</span></td>`;table.tBodies[0].appendChild(row);});list.appendChild(table);list.onchange=updateCount;updateCount();};
        groupSelect.onchange=async()=>{status.textContent='Carregando aldeias do grupo…';groupSelect.disabled=true;try{await EAS.Data.Groups.ensureMembership(groupSelect.value);renderVillages();status.textContent='';}catch(error){EAS.UI.showStatus({target:status,message:error.message,type:'error'});}finally{groupSelect.disabled=false;}};
        selectAll.onclick=()=>{list.querySelectorAll('input[type="checkbox"]').forEach((input)=>input.checked=true);updateCount();};clearAll.onclick=()=>{list.querySelectorAll('input[type="checkbox"]').forEach((input)=>input.checked=false);updateCount();};
        intervalInput.onchange=()=>{intervalInput.value=String(Math.max(1,Number(intervalInput.value)||1));};
        start.onclick=()=>{const ids=selectedIds();if(!ids.length)return;const group=EAS.Data.Groups.getById(groupSelect.value);try{EAS.MassFarmExecution.start({groupId:groupSelect.value,groupName:group?.name||'Todos',villageIds:ids,template:templateSelect.value,intervalMs:Math.max(1000,Number(intervalInput.value)*1000)});EAS.UI.showStatus({target:status,message:'Execução aberta em uma aba auxiliar.',type:'success'});}catch(error){EAS.UI.showStatus({target:status,message:error.message,type:'error'});}};
        renderVillages();return win;
    }};
})();
