(() => {
    'use strict';
    EAS.Data ||= {}; EAS.State ||= {};
    const TTL = Object.freeze({ villages: 30 * 60 * 1000, troops: 5 * 60 * 1000, market: 2 * 60 * 1000, resources: 60 * 1000, merchants: 60 * 1000, server: 24 * 60 * 60 * 1000 });
    const invalid = new Map(); const inFlight = new Map(); const listeners = new Set();
    const emit = (event) => { listeners.forEach((listener) => { try { listener(event); } catch (error) { EAS.Log?.error?.('data', 'subscriber-error', error); } }); try { window.dispatchEvent(new CustomEvent('eas:data-updated', { detail: event })); } catch {} };
    const dedupe = (key, factory) => { if (inFlight.has(key)) return inFlight.get(key); const mark = EAS.Utils.Perf?.start?.('data.refresh', { key }); const promise = Promise.resolve().then(factory).then((value) => { EAS.Utils.Perf?.end?.(mark, { success: true }); return value; }, (error) => { EAS.Utils.Perf?.end?.(mark, { success: false }); EAS.Log?.error?.('data', 'refresh-failed', error, { state: key }); throw error; }).finally(() => inFlight.delete(key)); inFlight.set(key, promise); return promise; };
    const metadata = (domain, source = {}, count = 0) => { const updatedAt = Number(source.updatedAt || source.updatedAtLocal || source.updatedAtServer || 0); const ageMs = updatedAt ? Date.now() - updatedAt : Infinity; return { domain, source: source.source || 'cache', updatedAt, ageMs, ttlMs: TTL[domain], stale: invalid.has(domain) || ageMs > TTL[domain], confidence: count > 0 && !source.error ? (ageMs <= TTL[domain] ? 'high' : 'stale') : 'low', count, invalidatedBecause: invalid.get(domain) || null }; };
    const invalidate = (domain, reason = 'manual', villageId = null) => { invalid.set(domain, { reason, villageId, timestamp: Date.now() }); EAS.Log?.info?.('data', 'invalidated', { domain, reason, villageId }); emit({ type: 'invalidated', domain, reason, villageId }); };
    const clearInvalid = (domain) => invalid.delete(domain);
    const villages = { get: () => EAS.Villages.getAll(), getAll: () => EAS.Villages.getAll(), getById: (id) => EAS.Villages.getById(id), refresh: (options = {}) => dedupe('villages:all', async () => { const result = await EAS.Villages.refresh(options); clearInvalid('villages'); emit({ type: 'updated', domain: 'villages' }); return result; }), ensureFresh: (options = {}) => dedupe('villages:ensure', async () => { const result = await EAS.Villages.ensureFresh({ maxAgeMs: options.maxAgeMs ?? TTL.villages, forceRefresh: options.forceRefresh || invalid.has('villages') }); clearInvalid('villages'); return result; }), invalidate: (reason) => { invalidate('villages', reason); EAS.Villages.invalidate(reason); }, getMetadata: () => metadata('villages', EAS.Villages.getState(), EAS.Villages.getAll().length) };
    const troopsValue = () => Object.fromEntries(Object.entries(EAS.Troops.getAll()).map(([id, value]) => [id, { ...value, ownHome: value.ownHome || value.available || value.troops || {}, inVillage: value.inVillage || value.home || value.available || value.troops || {}, available: value.ownHome || value.available || value.troops || {}, home: value.inVillage || value.home || value.available || value.troops || {}, allOwn: value.allOwn || value.own || {}, own: value.allOwn || value.own || {}, support: value.support || {}, outside: value.outside || {}, inTransit: value.inTransit || {}, total: value.total || {}, recruiting: value.recruiting || {}, reserved: value.reserved || {}, updatedAt: value.updatedAt || EAS.Troops.getSourceInfo().updatedAtLocal || 0 }]));
    const troopTypes = Object.freeze({ available: 'ownHome', own: 'allOwn', home: 'inVillage', support: 'support', outside: 'outside', inTransit: 'inTransit' });
    const troopUnits = () => { const configured = EAS.World?.getGameData?.().units; const units = Array.isArray(configured) ? configured : configured && typeof configured === 'object' ? Object.keys(configured) : []; return [...new Set([...(EAS.Troops.getSourceInfo().unitOrder || []), ...units])]; };
    const aggregateTroops = ({ groupId = 'all', type = 'available' } = {}) => { const field = troopTypes[type] || 'ownHome'; const ownedIds = new Set(villages.getAll().map((village) => String(village.id))); const groupIds = new Set(groupId === 'all' ? ownedIds : (EAS.Groups?.getVillageIds?.(groupId) || []).map(String)); const entries = Object.entries(troopsValue()).filter(([id]) => ownedIds.has(String(id)) && groupIds.has(String(id))); const units = troopUnits(); const totals = Object.fromEntries(units.map((unit) => [unit, entries.reduce((sum, [, value]) => sum + Math.max(0, Number(value[field]?.[unit] || 0)), 0)])); const supportedTypes = new Set(EAS.Troops.getSourceInfo().rowTypes || ['available','home']); return { groupId: String(groupId), type, field, supported: supportedTypes.has(type), villageCount: entries.length, villageIds: entries.map(([id]) => String(id)), units, totals, source: 'EAS.Data.Troops', metadata: troops.getMetadata() }; };
    const troops = { get: troopsValue, getAll: troopsValue, getById: (id) => troopsValue()[String(id)] || null, aggregate: aggregateTroops, getSupportedTypes: () => [...new Set(EAS.Troops.getSourceInfo().rowTypes || ['available','home'])], getUnits: troopUnits, refresh: (options = {}) => dedupe('troops:all', async () => { const result = await EAS.Troops.refresh(options); clearInvalid('troops'); emit({ type: 'updated', domain: 'troops' }); return result; }), ensureFresh: (options = {}) => dedupe('troops:ensure', async () => { const result = await EAS.Troops.ensureLoaded({ maxAgeMs: options.maxAgeMs ?? TTL.troops, forceRefresh: options.forceRefresh || invalid.has('troops') }); clearInvalid('troops'); return result; }), invalidate: (reason, villageId) => invalidate('troops', reason, villageId), getMetadata: () => metadata('troops', EAS.Troops.getSourceInfo(), Object.keys(troopsValue()).length) };
    const groups = { get: () => EAS.Groups?.getAll?.() || [], getAll() { return this.get(); }, getById: (id) => EAS.Groups?.getById?.(id) || null, getVillageIds: (id) => EAS.Groups?.getVillageIds?.(id) || [], refresh: async () => groups.get(), ensureFresh: async () => groups.get(), invalidate: () => {}, getMetadata: () => EAS.Groups?.getMetadata?.() || { source: 'unavailable', count: 0, remoteRequests: 0 } };
    const marketCache = () => EAS.MarketEngine.getCache();
    const marketVillages = () => EAS.MarketEngine.cacheVillages(marketCache()).map(EAS.MarketEngine.withEconomicState);
    const marketSnapshot = () => { const cache = marketCache(); const villages = marketVillages(); return { ...cache, villages: Object.fromEntries(villages.map((village) => [village.villageId, village])), economicStates: Object.fromEntries(villages.map((village) => [village.villageId, village.economic])) }; };
    const market = {
        get: marketSnapshot,
        getAll: marketVillages,
        getById: (id) => marketVillages().find((village) => String(village.villageId || village.id) === String(id)) || null,
        refresh: ({ villageId, villageIds, forceRefresh = true, maxAgeMs, ...options } = {}) => {
            const ids = (villageIds || (villageId != null ? [villageId] : (EAS.Villages?.getAll?.() || EAS.Villages?.list?.() || []).map((village) => village.id))).map(String);
            const key = `market:economic:${[...ids].sort().join(',') || 'all'}:${forceRefresh ? 'force' : `max-age-${maxAgeMs ?? TTL.market}`}`;
            return dedupe(key, async () => { const executionId = options.executionId || `market-refresh-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; EAS.Log?.info?.('data.market', 'refresh.start', { executionId, villageIds: ids, forceRefresh }); try { const networkState = await EAS.MarketEngine.refreshMarketNetworkState({ villageIds: ids.length ? ids : undefined, maxAgeMs: maxAgeMs ?? (forceRefresh ? 0 : TTL.market), ...options, executionId }); if (!networkState.refresh?.cancelled) { clearInvalid('market'); clearInvalid('resources'); clearInvalid('merchants'); } const result = { ...marketSnapshot(), refresh: networkState.refresh || { executionId, cancelled: false } }; emit({ type: networkState.refresh?.cancelled ? 'refresh-cancelled' : 'updated', domain: 'market', villageIds: ids, executionId }); EAS.Log?.info?.('data.market', networkState.refresh?.cancelled ? 'refresh.cancelled' : 'refresh.complete', { executionId, villageCount: ids.length, refresh: networkState.refresh }); return result; } catch (error) { EAS.Log?.error?.('data.market', 'refresh.error', error, { executionId, state: 'refreshing' }); throw error; } finally { EAS.Log?.debug?.('data.market', 'refresh.cleanup', { executionId, key }); } });
        },
        ensureFresh: (options = {}) => { const meta = metadata('market', marketCache(), marketVillages().length); return !options.forceRefresh && !meta.stale ? Promise.resolve(marketSnapshot()) : market.refresh({ ...options, forceRefresh: true }); },
        invalidate: (reason, villageId) => { invalidate('market', reason, villageId); invalidate('resources', reason, villageId); invalidate('merchants', reason, villageId); },
        getMetadata: () => metadata('market', marketCache(), marketVillages().length)
    };
    const projectionDomain = (name, selector) => ({ get: () => Object.fromEntries(marketVillages().map((village) => [String(village.villageId), selector(village)])), getAll() { return this.get(); }, getById(id) { return this.get()[String(id)] || null; }, refresh: (options) => market.refresh(options), ensureFresh: (options) => market.ensureFresh(options), invalidate: (reason, villageId) => invalidate(name, reason, villageId), getMetadata: () => metadata(name, marketCache(), marketVillages().length) });
    const server = { get: () => ({ now: EAS.World.getServerNowTimestamp?.() || Date.now(), world: EAS.World.getWorldName?.(), timezone: 'America/Sao_Paulo' }), getAll() { return this.get(); }, getById: () => null, refresh: async () => server.get(), ensureFresh: async () => server.get(), invalidate: (reason) => invalidate('server', reason), getMetadata: () => ({ ...metadata('server', { source: 'game-data', updatedAt: Date.now() }, 1), stale: false }) };
    Object.assign(EAS.Data, { TTL, Villages: villages, VillageGroups: groups, Troops: troops, Market: market, Resources: projectionDomain('resources', (village) => EAS.MarketEngine.getProjectedResources(village)), Merchants: projectionDomain('merchants', (village) => ({ ...village.merchants })), Server: server, dedupe, invalidate, subscribe(listener) { listeners.add(listener); return () => listeners.delete(listener); }, async mapLimit(items, limit, worker) { const results = new Array(items.length); let cursor = 0; const runners = Array.from({ length: Math.min(Math.max(1, limit), items.length) }, async () => { while (cursor < items.length) { const index = cursor++; results[index] = await worker(items[index], index); } }); await Promise.all(runners); return results; }, async refreshStale(names = ['Villages','Market','Troops']) { const selected = names.map((name) => EAS.Data[name]).filter(Boolean); const stale = selected.filter((domain) => domain.getMetadata().stale); EAS.Usage?.track?.('data.refreshStale', { domains: stale.map((domain) => domain.getMetadata().domain) }); return Promise.allSettled(stale.map((domain) => domain.ensureFresh({ forceRefresh: true }))); }, onTransportSent({ originVillageId, targetVillageId } = {}) { market.invalidate('transport-sent', originVillageId); invalidate('resources', 'transport-sent', targetVillageId); invalidate('merchants', 'transport-sent', originVillageId); }, onOfferCreated({ villageId } = {}) { invalidate('market', 'offer-created', villageId); invalidate('resources', 'offer-created', villageId); invalidate('merchants', 'offer-created', villageId); }, onAttackSent({ originVillageId } = {}) { troops.invalidate('attack-sent', originVillageId); }, async bootstrap() { const mark = EAS.Utils.Perf?.start?.('hub.bootstrap'); const snapshot = EAS.State.snapshot(); Promise.allSettled([villages.ensureFresh(), market.ensureFresh()]).then(() => emit({ type: 'bootstrap-refreshed' })); EAS.Utils.Perf?.end?.(mark, { backgroundRefresh: true }); return snapshot; } });
    EAS.State.snapshot = () => { const generatedAt = Date.now(); const domains = { villages: villages.getAll(), groups: groups.getAll(), troops: troops.getAll(), market: market.get(), resources: EAS.Data.Resources.get(), merchants: EAS.Data.Merchants.get(), server: server.get() }; return { generatedAt, ...domains, metadata: { ...Object.fromEntries(['Villages','Troops','Market','Resources','Merchants','Server'].map((name) => [name.toLowerCase(), EAS.Data[name].getMetadata()])), groups: groups.getMetadata() } }; };
})();
